version: '3'

services:
  cli:
    build:
      context: ./cli
      dockerfile: Dockerfile.svc
      args:
        SVC_PORT: ${SVC_PORT}
    image: llm-chatbot-image-svc
    container_name: llm-chatbot-svc
    ports:
      - "${SVC_PORT}:${SVC_PORT}"
    volumes:
      - ${CONTEXT_DIR}:/usr/app/context
      - ${LLMS_DIR}:/usr/app/llms
    networks:
      - llm-chatbot-network

  api:
    build: 
      context: ./api
      args:
        API_PORT: ${API_PORT}
    image: llm-chatbot-api-image
    container_name: llm-chatbot-api
    depends_on:
      - cli
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - LLM_CHATBOT_BASE_URL=${LLM_CHATBOT_BASE_URL}
    networks:
      - llm-chatbot-network

networks:
  llm-chatbot-network:
    driver: bridge