version: '3'

services:
  # Base image for CLI
  # cli-base:
  #   build:
  #     context: ./cli
  #     dockerfile: Dockerfile.svc_base
  #   image: llm-chatbot-image-svc-base

  # Base image for API
  # api-base:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile.base
  #   image: llm-chatbot-api-image-base

  cli:
    build:
      context: ./cli
      dockerfile: Dockerfile.svc
      args:
        SVC_PORT: ${SVC_PORT}
      target: final
    image: llm-chatbot-image-svc
    container_name: llm-chatbot-svc
    ports:
      - "${SVC_PORT}:${SVC_PORT}"
    volumes:
      - ${CONTEXT_DIR}:/usr/app/context
      - ${LLMS_DIR}:/usr/app/llms
    networks:
      - llm-chatbot-network
    #depends_on:
    #  - cli-base

  api:
    build: 
      context: ./api
      args:
        API_PORT: ${API_PORT}
      target: final
    image: llm-chatbot-api-image
    container_name: llm-chatbot-api
    depends_on:
      #- api-base
      - cli
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - LLM_CHATBOT_BASE_URL=${LLM_CHATBOT_BASE_URL}
    networks:
      - llm-chatbot-network

networks:
  llm-chatbot-network:
    driver: bridge